### ISSUE TITLE
Syncing yuzu saves to ryujinx crashes ryu

### ISSUE THREAD

**Issue by TopHatMan** [minhnhattonthat/ryujinx-tool#1]
So I used your script , I had make few edits to make it work with my filepaths. well the program works it syncs my saves to ryu but when I load any game the game will crash.

Any idea on that?
https://pastebin.com/XZhV97cr

my edited py

https://pastebin.com/Jt0AybBG

My hunch is that user profile is not same id.

**Comment by KruyKaze** [comment]
I can confirm this happened to me with Zelda tears of the kingdom. It no longer loads with yuzu or ryujinx

**Comment by minhnhattonthat** [comment]
Hi, first of all, thank you for using the tool, and sorry for any trouble it caused you.

I can reproduce with Zelda TotK like @KruyKaze said. I think it relates to games with bcat save as the termination code is ResultFsTargetNotFound (2002-1002), which is similar to this [issue](https://github.com/Ryujinx/Ryujinx/issues/4149)

I will need sometimes to fix this issue. As a temporary work around, please make another fresh instance of ryujinx and play zela totk with it. You can manually copy the save to this instance.

Also @TopHatMan , do you face this issue with any other game? as currently it only happens to zelda totk for me. The log shown the same termination code so I'm not sure if your issue is any different from mine.

**Comment by TopHatMan** [comment]
all games with yuzu saves crash.

**Comment by minhnhattonthat** [comment]
I fixed the crash with c0be30c79f9e1cc0a76665b1d1ab49fbc55f8c7b.
@KruyKaze @TopHatMan would you mind try the updated script to see if it's working?
If not, can you zip your entire Ryujinx folder for me to check?
TIA

**Comment by KruyKaze** [comment]
> I fixed the crash with [c0be30c](https://github.com/minhnhattonthat/ryujinx-tool/commit/c0be30c79f9e1cc0a76665b1d1ab49fbc55f8c7b). @KruyKaze @TopHatMan would you mind try the updated script to see if it's working? If not, can you zip your entire Ryujinx folder for me to check? TIA

I initially was playing TOTK on Yuzu then it stopped working on both.
Now I just ran the new script and I can load TOTK on Ryujinx but it still crashes and doesn't load on Yuzu.
Do you still want the zip file?
Thanks

**Comment by minhnhattonthat** [comment]
> > I fixed the crash with [c0be30c](https://github.com/minhnhattonthat/ryujinx-tool/commit/c0be30c79f9e1cc0a76665b1d1ab49fbc55f8c7b). @KruyKaze @TopHatMan would you mind try the updated script to see if it's working? If not, can you zip your entire Ryujinx folder for me to check? TIA
> 
> I initially was playing TOTK on Yuzu then it stopped working on both. Now I just ran the new script and I can load TOTK on Ryujinx but it still crashes and doesn't load on Yuzu. Do you still want the zip file? Thanks

If that's the case then can I have the log from yuzu please

**Comment by KruyKaze** [comment]
yes here 
[yuzu_log.txt](https://github.com/minhnhattonthat/ryujinx-tool/files/14552097/yuzu_log.txt)

**Comment by minhnhattonthat** [comment]
from your log I can only see you were trying to boot CHRONO CROSS with no error. Can you try getting a more updated log. also can you click "Open Save Data Location" from yuzu to check if save already existed for TotK?

**Comment by KruyKaze** [comment]
That means it's not even getting to saving the log. That is the the latest log.
Let me check the save data location

**Comment by KruyKaze** [comment]
oh my yuzu install might be broken. 
I use https://github.com/ordovice/batocera-switch to update my switch emulators.
I think it might have broken my Yuzu after the yuzu github was deleted

**Comment by KruyKaze** [comment]
Yep, the Yuzu appimage is no longer on my system

**Comment by KruyKaze** [comment]
I was able to restore the APPIMAGE files. And now the game loads.
The only issue now is that the time stamps are incorrect on saves . 
Thanks for the fix

**Comment by TopHatMan** [comment]
ok this fixed my issue and now ryu does not crash and loads games. However be advised I had to remove the "nand" comments from yuzu_dir for I use custom path and nand will not come up i.e this my custom folder /gddrive/NAND/user /gdrive/NAND/sys etc
