### ISSUE TITLE
syntax error invalid syntax

### ISSUE THREAD

**Issue by 5at0ri** [minhnhattonthat/ryujinx-tool#2]
im very new at this so its probably a mistake on my part but i have the folder with the repo, and put the prodkeys and hactool files in it. i installed python and when i try to run the ryujinxtool.py it opens and closes quickly, and when i try to open python and input the command lines such as syncing the yuzu saves it says invalid synatax with arrows pointing at the name 'ryujinktools.py'. id appreciate help on this, thank you.

**Comment by 5at0ri** [comment]
figuring it out myself rn

**Comment by 5at0ri** [comment]
![Screenshot 2024-04-10 025743](https://github.com/minhnhattonthat/ryujinx-tool/assets/165195527/252cfbc3-0df1-43c6-a13e-f04e8d727394)

i get this error and syntax errors when trying the commands after putting the contents of the folder in the /suluxan folder but is there a way to change where the repo folder can be?

**Comment by 5at0ri** [comment]
![Screenshot 2024-04-10 025947](https://github.com/minhnhattonthat/ryujinx-tool/assets/165195527/71090fe9-6366-48ea-b4c4-50cef39a44da)

this is where it is currently

**Comment by minhnhattonthat** [comment]
hi @5at0ri , sorry for the late reply. From what I see, you need to move your location to the `ryujinx-tool-main` folder. The command to do that after you open the terminal would be
`cd .\ryujinx-tool-main\`
then you can run the ryujinx command as normal

**Comment by 5at0ri** [comment]
Thanks for the reply, I'll try this later today. Once I run the command what should I expect to happen? Will there be confirmation messages of the synced files etc? Sorry for asking so many questions

**Comment by minhnhattonthat** [comment]
no worries. once you run the command, you will see a progress bar and a list of files being synced. so when it finished you will know which file is copy to where. also there is now a backup of the old save in the same folder of ryujinx_tool.py

**Comment by 5at0ri** [comment]
thank you! I just tried it and its working great, im grateful for you making such a useful tool :)

**Comment by 5at0ri** [comment]
@minhnhattonthat Is it possible to select two different save profiles (under user/save) that get transferred as some games use a different save folder? furthermore there are extra empty files created that are randomly added to either ryu or yuzu, is this meant to happen? the dlc and update command works perfect its just the game sync one thats being a bit weird for me, thanks.

edit - idk if its me doing something wrong but ryu ldn crashes on start up now so im just gonna leave it unless you know of a solution

**Comment by minhnhattonthat** [comment]
@5at0ri 

> Is it possible to select two different save profiles (under user/save) that get transferred as some games use a different save folder?

Currently it only supports 1 user profile for Ryujinx. I imagine managing multiple save profiles would be quite complicated.

>furthermore there are extra empty files created that are randomly added to either ryu or yuzu, is this meant to happen?

Yes, it's normal. Some games you played but have not created a save, will still create an empty save folder.

>idk if its me doing something wrong but ryu ldn crashes on start up now

Can you zip me the log files inside Logs folder to investigate?

Thanks

**Comment by 5at0ri** [comment]
@minhnhattonthat 
[ryu ldn crash at startup.zip](https://github.com/minhnhattonthat/ryujinx-tool/files/14970952/ryu.ldn.crash.at.startup.zip)
here is the zip, i just deleted LDN now so if you find a fix ill redownload it and try it again or maybe it was just an error that caused. thanks a lot for looking into this.

**Comment by minhnhattonthat** [comment]
@5at0ri sorry I cannot find any info related to the error in the log. Is this LDN version not updated as the main official one?
I may need the whole ryujinx folder to investigate further, or you can try make another clean install of ryujinx to see if the error still occurs

**Comment by 5at0ri** [comment]
It's okay I'll just leave it, the ldn version isn't as updated but thank you for your help :)
